### ISSUE TITLE
How to compile under Ubuntu 16.04

### ISSUE THREAD

**Issue by ecorov** [KengoSawa2/RapidCopy#1]
Hi, I have been searching copy tools on Linux system for a while but have no luck. I want to test RapdiCopy for coping my 800GB folder with 7 million small files. Could you tell me how to compile it under Ubuntu 16.04? I would compare how faster it is to cp command.

**Comment by KengoSawa2** [comment]
Hi, Thank you for interesting RapidCopy:)
I understand what you want to do.

Compile method is written in ReadMe Did you try it?
https://github.com/KengoSawa2/RapidCopy

I confirmed that I can compile with Ubuntu 14.04 LTS.
Ubuntu 16 has not confirmed, I think that I can compile like Ubuntu 14.
I think that it is not so difficult. cheers!!


Perhaps RapidCopy will be as fast as the cp command.
There are three good things about RapidCopy.

Do not interrupt even a large number of files
Enable differential copy faster than rsync(xxhash support)
operate with GUI, you can do the same operation on windows and Mac

**Comment by withr** [comment]
I didn't find the compile method. I am total have no idea using which method to compile? make make install?

You mentioned RapidCopy will be as fast as the cp command, so it will be faster than cp command, right? I just wrote a blog to share my experience of copy large folder with huge number of small files. But you may know quite well about it. http://withr.me/cp-rm-rsync/

**Comment by KengoSawa2** [comment]
In order to compile RapidCopy you need "Qt" framework and IDE "Qt Creator".
When "rapidcopy_main.pro" is loaded into QtCreator, "make" file is generated.

https://github.com/KengoSawa2/RapidCopy/blob/master/README.md

For now, building RapidCopy requires knowledge of Qt Framework.
#I think that it is not difficult as it reads the project file:)

If there are a lot of requests, I will make a compiled binary.
But I am busy now, so it will be a while later.

On the performance of RapidCopy:
I think that you should try it yourself.
Because I only have a simple test:)

**Comment by KengoSawa2** [comment]
Hi withr.

I fixed bugs in RapidCopy and confirmed it to compile and work with Ubuntu 16.04.
I needed to install libbsd and libacl with apt-get, but it was not particularly difficult.

Download Qt 5.6, start QtCreator, load rapidcopy_main.pro and select "Build".
You may try again if you have the chance.
I think it is difficult at the moment to make RapidCopy available without installing Qt.
